### ISSUE TITLE
HSV initial color's saturation and value drops to 0 

### ISSUE THREAD

**Issue by KrevedAccky** [GrenderG/Color-O-Matic#1]
When setting color mode to HSV and trying to set initial color, there's an issue. When saturation or value of color is less than maximum value, it drops down to 0 respectively in dialog window. There's no such problem with hue seekbar.

**Comment by GrenderG** [comment]
You can fix it and submit a pull request, otherwise I will look for the problem and fix it in a few days. Thanks for sharing this issue.

**Comment by GrenderG** [comment]
Solved in version 1.1.4.
